### ISSUE TITLE
Reseach cool and well-known NodeJS packages which help creating a CLI

### ISSUE THREAD

**Issue by fabiopagoti** [fabiopagoti/odata-to-postman#1]
Example:
https://www.npmjs.com/package/inquirer

Inquirer is good but the focus is on consecutive questions. The CLI would be better by having commands and flags for parameters like

`# odata-to-postman generate -e https://odata.service/v1/sample -u user -p pass1234 -o ./Downloads -f output_file.json`

in this example, 
`odata-to-postman` would be the main program
`generate` would be one of its commands
`-e`, `-u`, `-p`, `-o`, `-f` are just sample flags for endpoint, user, password and output directory and file name

(those are just examples)

It would be nice to have a NodeJS package which allows a CLI with many commands and flags.

**Comment by twentymurial33** [comment]
> It would be nice to have a NodeJS package which allows a CLI with many commands and flags.

https://github.com/GetStream/stream-cli

**Comment by twentymurial33** [comment]
1. Oclif https://oclif.io/     Documentation https://oclif.io/docs/introduction.html 


2.https://www.npmjs.com/package/caporal

**Comment by fabiopagoti** [comment]
> > It would be nice to have a NodeJS package which allows a CLI with many commands and flags.
> 
> https://github.com/GetStream/stream-cli

This one is a CLI which allows someone to communicate with this 'sream' stuff - but it does not help creating our own CLI.

**Comment by fabiopagoti** [comment]
> 

those 2 seems very promising - based on `caporal` and `inquirer` I found very interesting website which compares npm packages and I found some other alternatives as well.


https://npmcompare.com/compare/caporal,commander,inquirer,oclif,yargs
